version: '3'

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    volumes:
      - cockroachdb:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"

volumes:
  cockroachdb:
